# Generated by Django 2.2.26 on 2023-02-02 09:46
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Max, Q


def forward_add_current_job(apps, schema_editor):
    Device = apps.get_model("lava_scheduler_app", "Device")
    TestJob = apps.get_model("lava_scheduler_app", "TestJob")
    db_alias = schema_editor.connection.alias
    STATE_FINISHED = 5

    update_device = []
    for device_id, max_job in (
        TestJob.objects.using(db_alias)
        .filter(~Q(state=STATE_FINISHED), actual_device__isnull=False)
        .values_list("actual_device")
        .annotate(job=Max("pk"))
    ):
        device = Device(pk=device_id)
        device.current_job = TestJob(pk=max_job)
        update_device.append(device)

    Device.objects.bulk_update(update_device, ("current_job",))


def reverse_add_current_job(apps, schema_editor):
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0057_catchup_2023_january"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="current_job",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lava_scheduler_app.TestJob",
            ),
        ),
        migrations.RunPython(
            forward_add_current_job,
            reverse_add_current_job,
        ),
    ]
