# Generated by Django 2.2.26 on 2023-02-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0057_catchup_2023_january"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testjob",
            name="submit_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Submit time"),
        ),
        migrations.AddIndex(
            model_name="testjob",
            index=models.Index(
                fields=["-submit_time"], name="lava_schedu_submit__1a8a33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testjob",
            index=models.Index(
                fields=["-start_time"], name="lava_schedu_start_t_b7d703_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testjob",
            index=models.Index(
                fields=["-end_time"], name="lava_schedu_end_tim_cdac7b_idx"
            ),
        ),
    ]
