# Generated by Django 2.2.26 on 2023-06-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0057_dt_permissions_worker_master_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testjob",
            index=models.Index(
                condition=models.Q(
                    models.Q(_negated=True, state=5), ("actual_device__isnull", False)
                ),
                fields=["actual_device"],
                name="current_job_prefetch_index",
            ),
        ),
    ]
