# Generated by Django 4.2.28 on 2026-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lava_scheduler_app", "0069_testjob_metadata_gin_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="arch",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=32,
                null=True,
                verbose_name="Architecture",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="boot_time",
            field=models.DateTimeField(
                default=None,
                editable=False,
                help_text="When the worker last booted, derived from the uptime it reports. A change here means the worker rebooted.",
                null=True,
                verbose_name="Booted",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="cpu_model",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=128,
                null=True,
                verbose_name="CPU",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="kernel",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Kernel",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="load_1",
            field=models.FloatField(
                default=None,
                editable=False,
                null=True,
                verbose_name="Load average (1 minute)",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="load_15",
            field=models.FloatField(
                default=None,
                editable=False,
                null=True,
                verbose_name="Load average (15 minutes)",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="load_5",
            field=models.FloatField(
                default=None,
                editable=False,
                null=True,
                verbose_name="Load average (5 minutes)",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="mem_available",
            field=models.BigIntegerField(
                default=None,
                editable=False,
                help_text="Memory available for new work without swapping, which is not the same as unused memory: it counts reclaimable cache",
                null=True,
                verbose_name="Memory available",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="mem_total",
            field=models.BigIntegerField(
                default=None, editable=False, null=True, verbose_name="Memory size"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="nproc",
            field=models.PositiveSmallIntegerField(
                default=None, editable=False, null=True, verbose_name="Cores"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="tmp_dir",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                help_text="Directory the worker stores temporary job files in, which the disk figures below describe",
                max_length=256,
                null=True,
                verbose_name="Job temporary directory",
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="tmp_disk_free",
            field=models.BigIntegerField(
                default=None, editable=False, null=True, verbose_name="Job storage free"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="tmp_disk_total",
            field=models.BigIntegerField(
                default=None, editable=False, null=True, verbose_name="Job storage size"
            ),
        ),
    ]
