# Generated by Django 6.0.3 on 2026-09-10 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0070_increase_tag_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTypeQueueSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "queued_jobs",
                    models.PositiveIntegerField(
                        default=0, help_text="Jobs waiting for a device of this type."
                    ),
                ),
                (
                    "running_jobs",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Jobs reserved for or running on this device type.",
                    ),
                ),
                (
                    "available_devices",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Idle, healthy devices on an online worker.",
                    ),
                ),
                (
                    "started_jobs",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Jobs that started since the previous snapshot. This is the population average_wait_time is computed over.",
                    ),
                ),
                (
                    "average_wait_time",
                    models.DurationField(
                        blank=True,
                        help_text="Mean time between submission and start for the jobs counted in started_jobs. NULL when none started.",
                        null=True,
                    ),
                ),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_snapshots",
                        to="lava_scheduler_app.devicetype",
                    ),
                ),
            ],
            options={
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(
                        fields=["device_type", "-timestamp"],
                        name="lava_schedu_device__a34ad6_idx",
                    )
                ],
            },
        ),
    ]
