# Generated by Django 5.2.17 on 2026-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lava_scheduler_app", "0071_device_type_queue_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetypequeuesnapshot",
            name="average_duration",
            field=models.DurationField(
                blank=True,
                help_text="Mean time a device was occupied (start to end) by the jobs counted in finished_jobs. NULL when none finished.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="devicetypequeuesnapshot",
            name="finished_jobs",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Jobs that finished since the previous snapshot. This is the population average_duration is computed over.",
            ),
        ),
    ]
