permissions:
    contents: read
    checks: write
    id-token: write
    packages: write

name: Run all LAVA tests and docker builds
on: [workflow_dispatch, push, pull_request]
jobs:
  run-all-docker-build-jobs:
    strategy:
      fail-fast: false
      matrix:
        component: [dispatcher, server]
        arch: [amd64]
    uses: ./.github/workflows/docker-build-job.yml
    with:
      component: ${{ matrix.component }}
      arch: ${{ matrix.arch }}

  run-all-test-jobs:
    strategy:
      fail-fast: false
      matrix:
        component: [dispatcher, server]
        distro: [debian]
        arch: [amd64]
        version: [12, 13]
    uses: ./.github/workflows/generic-lava-test-job.yml
    with:
      component: ${{ matrix.component }}
      distro: ${{ matrix.distro }}
      arch: ${{ matrix.arch }}
      version: ${{ matrix.version }}

  update-factory-staging:
    needs: [run-all-docker-build-jobs, run-all-test-jobs]
    if: github.event_name == 'push' && startsWith(github.ref_name, 'qualcomm-20')
    uses: ./.github/workflows/update-factory-staging.yml
    with:
      image_tag: ${{ needs.run-all-docker-build-jobs.outputs.image_tag }}
    secrets: inherit

  update-dispatcher-factory-staging:
    needs: [run-all-docker-build-jobs, run-all-test-jobs]
    if: github.event_name == 'push' && startsWith(github.ref_name, 'qualcomm-20')
    uses: ./.github/workflows/update-dispatcher-factory-staging.yml
    with:
      image_tag: ${{ needs.run-all-docker-build-jobs.outputs.image_tag }}
    secrets: inherit

